In [1]:
import numpy as np
import pandas as pd

In [66]:
data = pd.read_csv("Company_Data.csv")
data

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0     9.50        138      73           11         276    120       Bad   42   
1    11.22        111      48           16         260     83      Good   65   
2    10.06        113      35           10         269     80    Medium   59   
3     7.40        117     100            4         466     97    Medium   55   
4     4.15        141      64            3         340    128       Bad   38   
..     ...        ...     ...          ...         ...    ...       ...  ...   
395  12.57        138     108           17         203    128      Good   33   
396   6.14        139      23            3          37    120    Medium   55   
397   7.41        162      26           12         368    159    Medium   40   
398   5.94        100      79            7         284     95       Bad   50   
399   9.71        134      37            0          27    120      Good   49   

     Education Urban   US  
0           17   Yes  Yes  
1           10   Yes  Yes  
2           12   Yes  Yes  
3           14   Yes  Yes  
4           13   Yes   No  
..         ...   ...  ...  
395         14   Yes  Yes  
396         11    No  Yes  
397         18   Yes  Yes  
398         12   Yes  Yes  
399         16   Yes  Yes  

[400 rows x 11 columns]

# creating numpy nd array

In [2]:
array1= np.array([1,3,5,7,2])

In [3]:
array1

array([1, 3, 5, 7, 2])

In [4]:
type(array1)

numpy.ndarray

In [6]:
arr= np.array([[1,3,5],[3,2,4]])
arr

array([[1, 3, 5],
       [3, 2, 4]])

In [21]:
arr0=np.zeros((3,4))
arr0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
arr1=np.ones((2,6))
arr1


array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [13]:
arr5=np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
arr6=np.arange(6,29)
arr6

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28])

In [19]:
#if we want the alternate no then we need to mention 2 and for the numbers with 
# difference of 3 we need to mention 3
arr6=np.arange(5,29,2)
arr6

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27])

In [20]:
arr6=np.arange(5,29,3)
arr6

array([ 5,  8, 11, 14, 17, 20, 23, 26])

In [28]:
arr7=np.linspace(10,20,4)
# first digit shows lower range sencond shows upper range and third shows how many parts we need to do within the range
arr7

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [5]:
arr8 = np.eye(8)
arr8

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

## array manupulation operations

In [12]:
 #numpy.reshape(): Change the shape of an array without modifying its data.

array1= np.array([1,3,5,7,2, 5])

reshape_arr = np.reshape(array1,(2,3))
reshape_arr

array([[1, 3, 5],
       [7, 2, 5]])

In [13]:
#numpy.transpose(): Transpose the rows and columns of an array.



array1= np.array([1,34,5,6,4,23])

transpose_array = np.transpose(array1)
transpose_array

array([ 1, 34,  5,  6,  4, 23])

In [15]:
# numpy.flatten() : convert a multidimetional array into 1 dimention

arr = np.array([[1, 2, 3], [4, 5, 6]])
one_D_array = arr.flatten()
one_D_array

array([1, 2, 3, 4, 5, 6])

In [3]:
# join concatenate() join array along with specific axis

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenate_= np.concatenate((arr1,arr2))
concatenate_

array([1, 2, 3, 4, 5, 6])

In [7]:
# np.vstack : stack array vertically ( along rows )

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

vertical_stack = np.vstack((arr1,arr2))
vertical_stack

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# np.hstack : stack array horizontally (along columns)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

horizontal_stack = np.hstack((arr1,arr2))
horizontal_stack

array([1, 2, 3, 4, 5, 6])

## array aggrigation 

In [3]:
# addtion of array 
arr = np.array([1, 2, 3, 4, 5])
total_sum = np.sum(arr)
total_sum

15

In [8]:
# mean of array
arr = np.array([1,2,3,4,5])
mean = np.mean(arr)
mean

3.0

In [9]:
# median 
arr = np.array([1,2,3,4,5])
median = np.median(arr)
median

3.0

In [10]:
# min and max
arr = np.array([1,2,3,4,5])
min_ = np.min(arr)
min_

1

In [12]:
# max
arr = np.array([1,2,3,4,5])
max_=np.max(arr)
max_

5

In [14]:
#numpy.argmin() and numpy.argmax(): Find the indices of the minimum and maximum values in an array.
arr = np.array([1,2,6,4,5])

min_value = np.argmin(arr)
max_value = np.argmax(arr)

print(min_value)
print(max_value)

# indicate the position in an array


0
2


In [15]:
#numpy.all() and numpy.any(): Test whether all or any elements along a specified axis evaluate to True.

arr = np.array([True, False, True])
all_true = np.all(arr)
any_true = np.any(arr)
print(all_true)
print(any_true)

False
True


## array comparison and bullien operation 

In [16]:
#numpy.equal(): Perform element-wise comparison for equality.
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

result  = np.equal(arr1, arr2)

print(result)

[ True  True  True]


In [19]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 3, 4])
result = np.equal(arr1, arr2)
print(result)

[ True False False]


In [20]:
#numpy.not_equal(): Perform element-wise comparison for inequality.
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 3, 4])
result = np.not_equal(arr1, arr2)
print(result)


[False  True  True]


In [30]:
# np.greater() : element wise comparison for greater than 
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 3, 4])
result = np.greater(arr1, arr2)
print(result)

[False False False]


In [31]:
# np.greater_equal() : element wise comparison for greater than or equal to 
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 3, 4])
result = np.greater_equal(arr1,arr2)

print(result)

[ True False False]


In [32]:
# np.less(): element wise comparison for less than 

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 3, 4])
result = np.less(arr1, arr2)
print(result)

[False  True  True]


In [33]:
# np.less_equal(): element wise comparison for less than or equal to 
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 3, 4])

result= np.less_equal(arr1, arr2)
print(result)

[ True  True  True]


In [38]:
# np.logical_and(): performs element wise logical and operator 
arr1 = np.array([True , False, True])
arr2 = np.array([False, True, True])
result = np.logical_and(arr1, arr2)
print(result)

[False False  True]


In [40]:
# np.logical_or(): performs element wise logical or operator
arr1 = np.array([True , False, True])
arr2 = np.array([False, False, True])
result = np.logical_or(arr1, arr2)
print(result)

[ True False  True]


In [41]:
#np.logical_not() : performs element wise logical not operation
arr1 = np.array([True , False, True])
result = np.logical_not(arr1)
print(result)

[False  True False]


In [44]:
# negation of and  operator 
arr1 = np.array([True , False, True])
arr2 = np.array([False, False, True])
result = np.logical_not(np.logical_or(arr1, arr2))
print(result)

[False  True False]


## arithmatic and mathematical operations 

In [45]:
# np.add(): element wise addition of two array 
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 3, 4])
result = np.add( arr2,arr1)
result

array([2, 5, 7])

In [47]:
# np.subtract(): element wise substraction of two array
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 3, 4])
result = np.subtract(arr1, arr2)
result

array([ 0, -1, -1])

In [50]:
# np.multiply(): element wise multiplication of two array
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 3, 4])
result = np.multiply(arr1, arr2)
result

array([ 1,  6, 12])

In [56]:
# np.divide(): element wise division of two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 3, 4])
result = np.divide(arr1, arr2)
result

array([1.        , 0.66666667, 0.75      ])

In [59]:
# np.power(): element wise exponential of an array
arr2 = np.array([1, 3, 4])
result = np.power(arr2, 2)
print("the result of array to the power 2 is", result)

the result of array to the power 2 is [ 1  9 16]


In [61]:
#np.sqrt(): perform element wise root of an array 
arr2 = np.array([1, 3, 4])
result = np.sqrt(arr2)
print(result)

[1.         1.73205081 2.        ]


## trignometric functions

In [64]:
angle = np.radians(30)
print("the converted 30 degree to radian is ", angle)
sine= np.sin(angle)
cosine= np.cos(angle)
tan= np.tan(angle)
print(sine)
print(cosine)
print(tan)

the converted 30 degree to radian is  0.5235987755982988
0.49999999999999994
0.8660254037844387
0.5773502691896257


## array indexing and slicing 

In [67]:
data

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0     9.50        138      73           11         276    120       Bad   42   
1    11.22        111      48           16         260     83      Good   65   
2    10.06        113      35           10         269     80    Medium   59   
3     7.40        117     100            4         466     97    Medium   55   
4     4.15        141      64            3         340    128       Bad   38   
..     ...        ...     ...          ...         ...    ...       ...  ...   
395  12.57        138     108           17         203    128      Good   33   
396   6.14        139      23            3          37    120    Medium   55   
397   7.41        162      26           12         368    159    Medium   40   
398   5.94        100      79            7         284     95       Bad   50   
399   9.71        134      37            0          27    120      Good   49   

     Education Urban   US  
0           17   Yes  Yes  
1           10   Yes  Yes  
2           12   Yes  Yes  
3           14   Yes  Yes  
4           13   Yes   No  
..         ...   ...  ...  
395         14   Yes  Yes  
396         11    No  Yes  
397         18   Yes  Yes  
398         12   Yes  Yes  
399         16   Yes  Yes  

[400 rows x 11 columns]

In [91]:
data2 = data[4:100]
data2

# select from the 4 th row to 100

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
4    4.15        141      64            3         340    128       Bad   38   
5   10.81        124     113           13         501     72       Bad   78   
6    6.63        115     105            0          45    108    Medium   71   
7   11.85        136      81           15         425    120      Good   67   
8    6.54        132     110            0         108    124    Medium   76   
..    ...        ...     ...          ...         ...    ...       ...  ...   
95   5.58        134      25           10         237    148    Medium   59   
96   9.48        147      42           10         407    132      Good   73   
97   7.45        161      82            5         287    129       Bad   33   
98  12.49        122      77           24         382    127      Good   36   
99   4.88        121      47            3         220    107       Bad   56   

    Education Urban   US  
4          13   Yes   No  
5          16    No  Yes  
6          15   Yes   No  
7          10   Yes  Yes  
8          10    No   No  
..        ...   ...  ...  
95         13   Yes  Yes  
96         16    No  Yes  
97         16   Yes  Yes  
98         16    No  Yes  
99         16    No  Yes  

[96 rows x 11 columns]

In [95]:
COL= data[:,2] # access specific column of an 2d array 
COL

InvalidIndexError: (slice(None, None, None), 2)

In [96]:
element  =  data[2,5]  # accessing specific element of an specific table
print(element)

KeyError: (2, 5)

## array aggrigation and statistical functions

In [99]:
# unique values in an array 
unique_valeus = np.unique(data['Urban'])
unique_valeus

array(['No', 'Yes'], dtype=object)

In [106]:
# median of an array
population_median = np.median(data['Population'])
population_median

272.0

In [101]:
# mean of an array
population_mean = np.mean(data['Population'])
population_mean

264.84

In [103]:
# variance of an array 
population_var = np.var(data['Population'])
population_var

21665.514399999996

In [104]:
# standard deviation of an array 
population_std = np.std(data['Population'])
population_std

147.19210033150554

In [105]:
# correlation coefficient of an array 
population_corrcoef = np.corrcoef(data['Population'])
population_corrcoef

1.0